services:
  php:
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: 1

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1